// Generated by CoffeeScript 1.5.0
var _HAS_GPLUS_ENABLED, _ON_LOGIN_PROMOTION, _PUBLIC_USERNAME, _SESSION_COOKIE_INDEX, _SIGNUP_TIME_SEC, _USER_EMAIL, _USER_ID;

_PUBLIC_USERNAME = 'greatghoul';

_SIGNUP_TIME_SEC = 3;

_USER_ID = 14;

_USER_EMAIL = 'greatghoul@gmail.com';

_ON_LOGIN_PROMOTION = {
  title: 'Google Reader will not be available after July 1, 2013',
  body: '',
  version: 2012
};

_HAS_GPLUS_ENABLED = false;

_SESSION_COOKIE_INDEX = 0;
