// Generated by CoffeeScript 1.5.0
var divided;

divided = 0;

document.onkeydown = function(event) {
  if (event.keyCode === 91) {
    return divided = 1;
  }
};

chrome.extension.onMessage.addListener(function(request, sender, sendResponse) {
  if (request.greeting === "getInfo") {
    return sendResponse({
      divided: divided
    });
  } else {
    return sendResponse({});
  }
});
