// Generated by CoffeeScript 1.5.0

$(function() {
  var goHome;
  goHome = function() {
    parent.$("body").toggleClass("settings");
    parent.$("#settings-frame").toggle();
    parent.$("#nav").toggle();
    return parent.$("#chrome").toggle();
  };
  return $("#close-settings-link").on("click", goHome);
});
