var
_USER_ID = "04615556534921976030",
_USER_NAME = "amoblin",
_USER_EMAIL = "amoblin@gmail.com",
_IS_BLOGGER_USER = true,
_SIGNUP_TIME_SEC = 1235737842,
_COMMAND_TOKEN = "//iBUVv2DNAQvKUc49u9o2ng",
_PUBLIC_USERNAME = "amoblin",
_IS_MULTILOGIN_ENABLED = true,
_SESSION_COOKIE_INDEX = 0,
_LOGIN_URL = "https://www.google.com/accounts/ServiceLogin?hl\x3dzh_CN\x26nui\x3d1\x26service\x3dreader\x26continue\x3dhttp://www.google.com/reader/view/",
_INPUT_STREAM_ID = "user/04615556534921976030/state/com.google/reading-list",
_START_TIME = new Date().getTime();
function DumpError(m) {}
(function(){try{var e=!0,h=null,i=!1;var aa=function(a,b,c,d){d=d||{};d._sn=["cfg",b,c].join(".");window.gbar.logger.ml(a,d)};var m=window.gbar=window.gbar||{},p=window.gbar.i=window.gbar.i||{},ba;function _tvn(a,b){var c=parseInt(a,10);return isNaN(c)?b:c}function _tvf(a,b){var c=parseFloat(a);return isNaN(c)?b:c}function _tvv(a){return!!a}function q(a,b,c){(c||m)[a]=b}m.bv={n:_tvn("2",0),r:"r_gc.r_pw.r_qf.",f:".36.40.46.49.51.55.",e:"",m:_tvn("2",1)};var ca=function(a){return function(){return m.bv.m==a}},da=ca(1),ea=ca(2);
q("sb",da);q("kn",ea);p.a=_tvv;p.b=_tvf;p.c=_tvn;p.i=aa;var r=window.gbar.i.i;var t=function(){},v=function(){},w=function(a){var b=new Image,c=fa;b.onerror=b.onload=b.onabort=function(){try{delete ga[c]}catch(a){}};ga[c]=b;b.src=a;fa=c+1},ga=[],fa=0;q("logger",{il:v,ml:t,log:w});var x=window.gbar.logger;var y={},ha={},A=[],ia=p.b("0.1",0.1),ja=p.a("1",e),ka=function(a,b){A.push([a,b])},la=function(a,b){y[a]=b},ma=function(a){return a in y},B={},C=function(a,b){B[a]||(B[a]=[]);B[a].push(b)},E=function(a){C("m",a)},na=function(a,b){var c=document.createElement("script");c.src=a;ja&&(c.async=e);Math.random()<ia&&(c.onerror=function(){c.onerror=h;t(Error("Bundle load failed: name="+(b||"UNK")+" url="+a))});(document.getElementById("xjsc")||document.body).appendChild(c)},
J=function(a){for(var b=0,c;(c=A[b])&&c[0]!=a;++b);c&&(!c[1].l&&!c[1].s)&&(c[1].s=e,F(2,a),c[1].url&&na(c[1].url,a),c[1].libs&&G&&G(c[1].libs))},oa=function(a){C("gc",a)},pa=h,qa=function(a){pa=a},F=function(a,b,c){if(pa){a={t:a,b:b};if(c)for(var d in c)a[d]=c[d];try{pa(a)}catch(g){}}};q("mdc",y);q("mdi",ha);q("bnc",A);q("qGC",oa);q("qm",E);q("qd",B);q("lb",J);q("mcf",la);q("bcf",ka);q("aq",C);q("mdd","");q("has",ma);q("trh",qa);q("tev",F);if(p.a("1")){var ra=p.a("1"),sa=p.a("1"),ta=p.a("1"),ua=window.gapi={},va=function(a,b){var c=function(){m.dgl(a,b)};ra?E(c):(C("gl",c),J("gl"))},wa={},xa=function(a){a=a.split(":");for(var b;(b=a.pop())&&wa[b];);return!b},G=function(a){function b(){for(var b=a.split(":"),d=0,g;g=b[d];++d)wa[g]=1;for(b=0;d=A[b];++b)d=d[1],(g=d.libs)&&(!d.l&&d.i&&xa(g))&&d.i()}m.dgl(a,b)},K=window.___jsl={};K.h="m;/_/abc-static/_/js/gapi/__features__/rt=j/ver=24Irvz2rJ1Q.en./sv=1/am=!VvZ7oDep-coJNQTnkA/d=1";K.ms="https://apis.google.com";
K.m="";K.l=[];ra||A.push(["gl",{url:"//ssl.gstatic.com/gb/js/abc/glm_e7bb39a7e1a24581ff4f8d199678b1b9.js"}]);var ya={pu:sa,sh:"",si:ta};y.gl=ya;q("load",va,ua);q("dgl",va);q("agl",xa);p.o=ra};var za=p.b("0.01",0.001),Aa=0;
function _mlToken(a,b){try{if(1>Aa){Aa++;var c,d=a,g=b||{},f=encodeURIComponent,j="es_plusone_gc_20130213.0_p0",k=["//www.google.com/gen_204?atyp=i&zx=",(new Date).getTime(),"&jexpid=",f("37102"),"&srcpg=",f("prop=32"),"&jsr=",Math.round(1/za),"&ogev=",f("0"),"&ogf=",m.bv.f,"&ogrp=",f(""),"&ogv=",f("1358516199.1362597341"),j?"&oggv="+f(j):"","&ogd=",f("com"),"&ogl=",f("zh-CN")];g._sn&&(g._sn="og."+
g._sn);for(var l in g)k.push("&"),k.push(f(l)),k.push("="),k.push(f(g[l]));k.push("&emsg=");k.push(f(d.name+":"+d.message));var n=k.join("");Ba(n)&&(n=n.substr(0,2E3));c=n;var u=window.gbar.logger._aem(a,c);w(u)}}catch(H){}}var Ba=function(a){return 2E3<=a.length},Ca=function(a,b){return b};function Da(a){t=a;q("_itl",Ba,x);q("_aem",Ca,x);q("ml",t,x);a={};y.er=a}p.a("")?Da(function(a){throw a;}):p.a("1")&&Math.random()<za&&Da(_mlToken);var _E="left",M=function(a,b){var c=a.className;L(a,b)||(a.className+=(""!=c?" ":"")+b)},N=function(a,b){var c=a.className,d=RegExp("\\s?\\b"+b+"\\b");c&&c.match(d)&&(a.className=c.replace(d,""))},L=function(a,b){var c=RegExp("\\b"+b+"\\b"),d=a.className;return!(!d||!d.match(c))},Ea=function(a,b){L(a,b)?N(a,b):M(a,b)};q("ca",M);q("cr",N);q("cc",L);p.k=M;p.l=N;p.m=L;p.n=Ea;var Fa=["gb_71","gb_155"],Ga;function Ha(a){Ga=a}function Ia(a){var b=Ga&&!a.href.match(/.*\/accounts\/ClearSID[?]/)&&encodeURIComponent(Ga());b&&(a.href=a.href.replace(/([?&]continue=)[^&]*/,"$1"+b))}function Ja(a){window.gApplication&&(a.href=window.gApplication.getTabUrl(a.href))}function Ka(a){try{var b=(document.forms[0].q||"").value;b&&(a.href=a.href.replace(/([?&])q=[^&]*|$/,function(a,c){return(c||"&")+"q="+encodeURIComponent(b)}))}catch(c){r(c,"sb","pq")}}
var La=function(){for(var a=[],b=0,c;c=Fa[b];++b)(c=document.getElementById(c))&&a.push(c);return a},Ma=function(){var a=La();return 0<a.length?a[0]:h},Na=function(){return document.getElementById("gb_70")},O={},P={},Oa={},Q={},R=void 0,Ta=function(a,b){try{var c=document.getElementById("gb");M(c,"gbpdjs");S();Pa(document.getElementById("gb"))&&M(c,"gbrtl");if(b&&b.getAttribute){var d=b.getAttribute("aria-owns");if(d.length){var g=document.getElementById(d);if(g){var f=b.parentNode;if(R==d)R=void 0,
N(f,"gbto");else{if(R){var j=document.getElementById(R);if(j&&j.getAttribute){var k=j.getAttribute("aria-owner");if(k.length){var l=document.getElementById(k);l&&l.parentNode&&N(l.parentNode,"gbto")}}}Qa(g)&&Ra(g);R=d;M(f,"gbto")}}}}E(function(){m.tg(a,b,e)});Sa(a)}catch(n){r(n,"sb","tg")}},Ua=function(a){E(function(){m.close(a)})},Va=function(a){E(function(){m.rdd(a)})},Pa=function(a){var b,c="direction",d=document.defaultView;d&&d.getComputedStyle?(a=d.getComputedStyle(a,""))&&(b=a[c]):b=a.currentStyle?
a.currentStyle[c]:a.style[c];return"rtl"==b},Xa=function(a,b,c){if(a)try{var d=document.getElementById("gbd5");if(d){var g=d.firstChild,f=g.firstChild,j=document.createElement("li");j.className=b+" gbmtc";j.id=c;a.className="gbmt";j.appendChild(a);if(f.hasChildNodes()){c=[["gbkc"],["gbf","gbe","gbn"],["gbkp"],["gbnd"]];for(var d=0,k=f.childNodes.length,g=i,l=-1,n=0,u;u=c[n];n++){for(var H=0,I;I=u[H];H++){for(;d<k&&L(f.childNodes[d],I);)d++;if(I==b){f.insertBefore(j,f.childNodes[d]||h);g=e;break}}if(g){if(d+
1<f.childNodes.length){var U=f.childNodes[d+1];!L(U.firstChild,"gbmh")&&!Wa(U,u)&&(l=d+1)}else if(0<=d-1){var V=f.childNodes[d-1];!L(V.firstChild,"gbmh")&&!Wa(V,u)&&(l=d)}break}0<d&&d+1<k&&d++}if(0<=l){var s=document.createElement("li"),D=document.createElement("div");s.className="gbmtc";D.className="gbmt gbmh";s.appendChild(D);f.insertBefore(s,f.childNodes[l])}m.addHover&&m.addHover(a)}else f.appendChild(j)}}catch(z){r(z,"sb","al")}},Wa=function(a,b){for(var c=b.length,d=0;d<c;d++)if(L(a,b[d]))return e;
return i},Ya=function(a,b,c){Xa(a,b,c)},Za=function(a,b){Xa(a,"gbe",b)},$a=function(){E(function(){m.pcm&&m.pcm()})},ab=function(){E(function(){m.pca&&m.pca()})},bb=function(a,b,c,d,g,f,j,k,l,n){E(function(){m.paa&&m.paa(a,b,c,d,g,f,j,k,l,n)})},cb=function(a,b){O[a]||(O[a]=[]);O[a].push(b)},db=function(a,b){P[a]||(P[a]=[]);P[a].push(b)},eb=function(a,b){Oa[a]=b},fb=function(a,b){Q[a]||(Q[a]=[]);Q[a].push(b)},Sa=function(a){a.preventDefault&&a.preventDefault();a.returnValue=i;a.cancelBubble=e},gb=
h,Ra=function(a,b){S();if(a){hb(a,"正在打开&hellip;");T(a,e);var c="undefined"!=typeof b?b:1E4,d=function(){ib(a)};gb=window.setTimeout(d,c)}},jb=function(a){S();a&&(T(a,i),hb(a,""))},ib=function(a){try{S();var b=a||document.getElementById(R);b&&(hb(b,"此服务当前无法使用。%1$s请稍后重试。","%1$s"),T(b,e))}catch(c){r(c,"sb","sdhe")}},hb=function(a,b,c){if(a&&b){var d=Qa(a);if(d){if(c){d.innerHTML="";b=b.split(c);c=0;for(var g;g=b[c];c++){var f=document.createElement("div");f.innerHTML=g;d.appendChild(f)}}else d.innerHTML=
b;T(a,e)}}},T=function(a,b){var c=void 0!==b?b:e;c?M(a,"gbmsgo"):N(a,"gbmsgo")},Qa=function(a){for(var b=0,c;c=a.childNodes[b];b++)if(L(c,"gbmsg"))return c},S=function(){gb&&window.clearTimeout(gb)},kb=function(a){var b="inner"+a;a="offset"+a;return window[b]?window[b]:document.documentElement&&document.documentElement[a]?document.documentElement[a]:0},lb=function(){return i};q("so",Ma);q("sos",La);q("si",Na);q("tg",Ta);q("close",Ua);q("rdd",Va);q("addLink",Ya);q("addExtraLink",Za);q("pcm",$a);
q("pca",ab);q("paa",bb);q("ddld",Ra);q("ddrd",jb);q("dderr",ib);q("rtl",Pa);q("bh",O);q("abh",cb);q("dh",P);q("adh",db);q("ch",Q);q("ach",fb);q("eh",Oa);q("aeh",eb);ba=p.a("")?Ja:Ka;q("qs",ba);q("setContinueCb",Ha);q("pc",Ia);q("bsy",lb);p.d=Sa;p.j=kb;var mb={};y.base=mb;q("wg",{rg:{}});var nb={tiw:p.c("15000",0),tie:p.c("30000",0)};y.wg=nb;var ob={thi:p.c("10000",0),thp:p.c("180000",0),tho:p.c("5000",0),tet:p.b("0.5",0)};y.wm=ob;A.push(["m",{url:"//ssl.gstatic.com/gb/js/smm_b1a3ed21226b7e9e13fa7e04b9e2d5b5.js"}]);var pb={};y.heavy=pb;m.sg={c:""};if(p.a("1")){var qb=p.a("");A.push(["gc",{auto:qb,url:"//ssl.gstatic.com/gb/js/abc/gci_91f30755d6a6b787dcc2a4062e6e9824.js",libs:"googleapis.client:plusone"}]);var rb={version:"gci_91f30755d6a6b787dcc2a4062e6e9824.js",index:"0",lang:"zh-CN"};y.gc=rb;var sb=function(a){window.googleapis&&window.iframes?a&&a():(a&&oa(a),J("gc"))};q("lGC",sb);p.a("1")&&q("lPWF",sb)};window.__PVT="APfa0bo5iQnM72eThJFDFmD12HplmW4t2AxugGupWdUhiCEK7eaNORsnPMT-QgBNKBFj1FQphk40deEUqJkMZqRU4Ss6JePnfg==";if(p.a("1")&&p.a("1")){var tb=function(a){sb(function(){C("pw",a);J("pw")})};q("lPW",tb);A.push(["pw",{url:"//ssl.gstatic.com/gb/js/abc/pwm_45f73e4df07a0e388b0fa1f3d30e7280.js"}]);var ub=[],vb=function(a){ub[0]=a},wb=function(a,b){var c=b||{};c._sn="pw";t(a,c)},xb={signed:ub,elog:wb,base:"https://plusone.google.com/u/0",loadTime:(new Date).getTime()};y.pw=xb;var yb=function(a,b){for(var c=b.split("."),d=function(){var b=arguments;a(function(){for(var a=m,d=0,f=c.length-1;d<f;++d)a=a[c[d]];a[c[d]].apply(a,b)})},g=m,f=0,j=c.length-1;f<
j;++f)g=g[c[f]]=g[c[f]]||{};return g[c[f]]=d};yb(tb,"pw.clk");yb(tb,"pw.hvr");q("su",vb,m.pw)};var zb={F:1,I:2,fa:3,z:4,Y:5,N:6,G:7,O:8,ja:9,W:10,M:11,V:12,U:13,P:14,S:15,R:16,ha:17,C:18,Q:19,ia:20,ga:21,A:22,H:23,la:24,ma:25,ka:26,g:27,u:28,w:29,v:30,ea:31,aa:32,ba:33,K:34,L:35,da:36,ca:37,$:38,D:39,T:40,B:41,Z:42,X:43,J:500},Ab=[1,2,3,4,5,6,9,10,11,13,14,28,29,30,34,35,37,38,39,40,41,42,43,500];var Bb=p.b("0.001",1E-4),Cb=p.b("0.01",1),Db=i,Eb=i;if(p.a("1")){var Fb=Math.random();Fb<=Bb&&(Db=e);Fb<=Cb&&(Eb=e)}var Gb=zb,W=h;
function Hb(a,b){var c=Bb,d=Db,g;g=a;if(!W){W={};for(var f=0;f<Ab.length;f++){var j=Ab[f];W[j]=e}}if(g=!!W[g])c=Cb,d=Eb;if(d){var d=encodeURIComponent,k="es_plusone_gc_20130213.0_p0",l;m.rp?(l=m.rp(),l="-1"!=l?l:""):l="";g=(new Date).getTime();var f=a,j=d("37102"),n=d("0"),u=m.bv.f,H=d("32");l=d(l);var c=Math.round(1/c),I=d("1358516199.1362597341"),k=k?"&oggv="+d(k):"",U=d("com"),
V=d("zh-CN"),s,D=0;s=function(a,b){p.a(b)&&(D|=a)};s(1,"1");s(2,"1");s(4,"");s(8,"");s=D;g=["//www.google.com/gen_204?atyp=i&zx=",g,"&oge=",f,"&ogex=",j,"&ogev=",n,"&ogf=",u,"&ogp=",H,"&ogrp=",l,"&ogsr=",c,"&ogv=",I,k,"&ogd=",U,"&ogl=",V,"&ogus=",s];if(b){"ogw"in b&&(g.push("&ogw="+b.ogw),delete b.ogw);var z,f=b,j=[];for(z in f)0!=j.length&&j.push(","),j.push(Ib(z)),j.push("."),j.push(Ib(f[z]));z=j.join("");""!=z&&(g.push("&ogad="),g.push(d(z)))}w(g.join(""))}}
function Ib(a){"number"==typeof a&&(a+="");return"string"==typeof a?a.replace(".","%2E").replace(",","%2C"):a}v=Hb;q("il",v,x);var Jb={};y.il=Jb;var Kb=function(a,b,c,d,g,f,j,k,l,n){E(function(){m.paa(a,b,c,d,g,f,j,k,l,n)})},Lb=function(){E(function(){m.prm()})},Mb=function(a){E(function(){m.spn(a)})},Nb=function(a){E(function(){m.sps(a)})},Ob=function(a){E(function(){m.spp(a)})},Pb={"27":"//lh3.googleusercontent.com/-J_yUc0lHIho/AAAAAAAAAAI/AAAAAAAAAAA/ZUX4pFkearM/s27-c/photo.jpg","27":"//lh3.googleusercontent.com/-J_yUc0lHIho/AAAAAAAAAAI/AAAAAAAAAAA/ZUX4pFkearM/s27-c/photo.jpg","27":"//lh3.googleusercontent.com/-J_yUc0lHIho/AAAAAAAAAAI/AAAAAAAAAAA/ZUX4pFkearM/s27-c/photo.jpg"},Qb=function(a){return(a=Pb[a])||"//lh3.googleusercontent.com/-J_yUc0lHIho/AAAAAAAAAAI/AAAAAAAAAAA/ZUX4pFkearM/s27-c/photo.jpg"},
Rb=function(){E(function(){m.spd()})};q("spn",Mb);q("spp",Ob);q("sps",Nb);q("spd",Rb);q("paa",Kb);q("prm",Lb);cb("gbd4",Lb);
if(p.a("1")){var Sb={d:p.a(""),e:"amoblin@gmail.com",sanw:p.a("1"),p:"//lh3.googleusercontent.com/-J_yUc0lHIho/AAAAAAAAAAI/AAAAAAAAAAA/ZUX4pFkearM/s96-c/photo.jpg",cp:"1",xp:p.a("1"),mg:"%1$s（已授权）",md:"%1$s（默认）",mh:"276",s:"1",pp:Qb,ppl:p.a(""),ppa:p.a("1"),ppm:"Google+ 信息页"};
y.prf=Sb};var X,Tb,Y,Ub,Z=0,Vb=function(a,b,c){if(a.indexOf)return a.indexOf(b,c);if(Array.indexOf)return Array.indexOf(a,b,c);for(c=c==h?0:0>c?Math.max(0,a.length+c):c;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},$=function(a,b){return-1==Vb(a,Z)?(r(Error(Z+"_"+b),"up","caa"),i):e},Xb=function(a,b){$([1,2],"r")&&(X[a]=X[a]||[],X[a].push(b),2==Z&&window.setTimeout(function(){b(Wb(a))},0))},Yb=function(a,b,c){if($([1],"nap")&&c){for(var d=0;d<c.length;d++)Tb[c[d]]=e;m.up.spl(a,b,"nap",c)}},Zb=function(a,
b,c){if($([1],"aop")&&c){if(Y)for(var d in Y)Y[d]=Y[d]&&-1!=Vb(c,d);else{Y={};for(d=0;d<c.length;d++)Y[c[d]]=e}m.up.spl(a,b,"aop",c)}},$b=function(){try{if(Z=2,!Ub){Ub=e;for(var a in X)for(var b=X[a],c=0;c<b.length;c++)try{b[c](Wb(a))}catch(d){r(d,"up","tp")}}}catch(g){r(g,"up","mtp")}},Wb=function(a){if($([2],"ssp")){var b=!Tb[a];Y&&(b=b&&!!Y[a]);return b}};Ub=i;X={};Tb={};Y=h;
var Z=1,ac=function(){try{return!!window.localStorage&&"object"==typeof window.localStorage}catch(a){return i}},bc=function(a){return a&&a.style&&a.style.na&&"undefined"!=typeof a.load},cc=function(a,b,c,d){try{d||(b="og-up-"+b),ac()?window.localStorage.setItem(b,c):bc(a)&&(a.setAttribute(b,c),a.save(a.id))}catch(g){g.code!=DOMException.QUOTA_EXCEEDED_ERR&&r(g,"up","spd")}},dc=function(a,b,c){try{c||(b="og-up-"+b);if(ac())return window.localStorage.getItem(b);if(bc(a))return a.load(a.id),a.getAttribute(b)}catch(d){d.code!=
DOMException.QUOTA_EXCEEDED_ERR&&r(d,"up","gpd")}return""},ec=function(a,b,c){a.addEventListener?a.addEventListener(b,c,i):a.attachEvent&&a.attachEvent("on"+b,c)},fc=function(a){for(var b=0,c;c=a[b];b++){var d=m.up;c=c in d&&d[c];if(!c)return i}return e};q("up",{r:Xb,nap:Yb,aop:Zb,tp:$b,ssp:Wb,spd:cc,gpd:dc,aeh:ec,aal:fc});var gc=function(a,b){a[b]=function(c){var d=arguments;m.qm(function(){a[b].apply(this,d)})}};gc(m.up,"sl");gc(m.up,"si");gc(m.up,"spl");
m.mcf("up",{sp:p.b("0.01",1)});function hc(){function a(){if(document.getElementById("gb")==h)v(Gb.g,{_m:"nogb"});else{for(var b;(b=f[j++])&&!("m"==b[0]||b[1].auto););b&&(F(2,b[0]),b[1].url&&na(b[1].url,b[0]),b[1].libs&&G&&G(b[1].libs));j<f.length&&setTimeout(a,0)}}function b(){0<g--?setTimeout(b,0):a()}var c=p.a("1"),d=p.a(""),g=3,f=A,j=0,k=window.gbarOnReady;if(k)try{k()}catch(l){r(l,"mle","or")}if(d)q("ldb",a);else if(c){var c=window,d="load",n=b,k="on"+d;if(c.addEventListener)c.addEventListener(d,
n,i);else if(c.attachEvent)c.attachEvent(k,n);else{var u=c[k];c[k]=function(){var a=u.apply(this,arguments),b=n.apply(this,arguments);return void 0==a?b:void 0==b?a:b&&a}}}else b()}q("rdl",hc);}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var c=window.gbar.i.i;var e=window.gbar;var f={};function g(a,b){f[a]||(f[a]=[]);f[a].push(b)}function h(a){if(a.type)for(var b=f[a.type],d=0;b&&d<b.length;++d)try{b[d](a)}catch(i){c(i,"sbc","d")}}e.bc={subscribe:g,dispatch:h};}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;var b=a.i;a.mcf("sw",{uo:"",s:"https",h:"plus.google.com",po:"",pa:"/u/0/_/notifications/frame",q:"sourceid=32",f:"pid=32",ipd:b.c("5",5),it:b.c("60",-1),l:"zh-CN",sto:b.c("10",10),mnr:b.c("0",0),co:b.a(""),obc:b.a(""),siu:"https://www.google.com/accounts/ServiceLogin?service=reader&passive=1209600&continue=http://www.google.com/reader/view/&followup=http://www.google.com/reader/view/"});}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;var b=[],d=function(c){b.push(c)};a.nuc=b;a.anuc=d;var e=function(){a.aq("m",function(){a.lni()})};a.lni=e;a.mcf("no",{ht:parseInt("100",10),n:"通知",es:parseInt("1",10),s:"https",h:"plus.google.com",po:"",fpmsec:parseInt("0",10),xuo:"",xhm:"POST",xpa:"/u/0/_/n/gcosuc"});}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;var b=[],d=function(c){b.push(c)};a.smc=b;a.asmc=d;a.mcf("sb",{ht:parseInt("100",10),n:"分享"});}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;var c=function(b){return!/AppleWebKit\/.+(?:Version\/3\.|Chrome\/[01]\.)/.test(b)},d=c;a.bs_w=function(){return window.navigator&&window.navigator.userAgent?d(window.navigator.userAgent):!1};}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;a.mcf("sf",{});}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var aa=window.gbar.i.i;var a=window.gbar;var e=a.i;var i,l;var s=function(b,d){aa(b,"es",d)},t=function(b){return document.getElementById(b)},u=function(b,d){var f=Array.prototype.slice.call(arguments,1);return function(){var c=Array.prototype.slice.call(arguments);c.unshift.apply(c,f);return b.apply(this,c)}},v=void 0,w=void 0,ga=e.c("840"),ha=e.c("640");e.c("840");
var ia=e.c("640"),ja=e.c("590"),ka=e.c("1514"),la=e.c("1474");e.c("1474");var ma=e.c("1252"),na=e.c("1060"),oa=e.c("995"),pa=e.c("851"),y={},z={},A={},B={},C={},D={},E={};y.h=e.c("102");y.m=e.c("44");y.f=e.c("220");
z.h=e.c("102");z.m=e.c("44");z.f=e.c("220");A.h=e.c("102");A.m=e.c("44");A.f=e.c("220");B.h=e.c("102");B.m=e.c("28");B.f=e.c("204");C.h=e.c("70");C.m=e.c("16");C.f=e.c("176");D.h=e.c("70");
D.m=e.c("16");D.f=e.c("176");E.h=e.c("70");E.m=e.c("12");E.f=e.c("136");
var F=e.c("16"),H=e.c("200"),qa=e.c("434"),ra=e.c("319"),sa=e.c("512"),ta=e.c("512"),ua=e.c("512"),va=e.c("434"),wa=e.c("319"),xa=e.c("220"),ya=e.c("220"),za=e.c("220"),
Aa=e.c("204"),Ba=e.c("176"),Ca=e.c("176"),Da=e.c("136"),Ea=e.c("15"),Fa=e.c("15"),I=e.c("15"),Ga=e.c("15"),Ha=e.c("6"),Ia=e.c("6"),Ja=e.c("6"),
Ka=e.c("44"),La=e.c("44"),Ma=e.c("44"),Na=e.c("28"),Oa=e.c("16"),Pa=e.c("16"),Qa=e.c("12"),Ra=e.c("30");e.a("1");
var Sa=e.c("700"),Ta="gb gbq gbu gbzw gbpr gbq2 gbqf gbqff gbq3 gbq4 gbq1 gbqlw gbql gbx1 gbx2 gbx3 gbx4 gbg1 gbg3 gbg4 gbd1 gbd3 gbd4 gbs gbwc gbprc".split(" "),K=["gbzw"],O=e.a(""),Ua=e.a(""),P=[],S=!0,U=function(b){try{a.close();var d=e.c("27");"xxl"==b?(T("gbexxl"),d=e.c("27")):"xl"==b?(T("gbexl"),d=e.c("27")):"lg"==b?(T(""),d=
e.c("27")):"md"==b?(T("gbem"),d=e.c("27")):"sm"==b?T("gbes"):"ty"==b?T("gbet"):"ut"==b&&T("gbeu");if(window.opera){var f=K.length;for(b=0;b<f;b++){var c=t(K[b]);if(c){var n=c.style.display;c.style.display="none";b+=0*c.clientHeight;c.style.display=n}}}a.sps(d)}catch(p){s(p,"stem")}},Va=u(U,"xxl"),Wa=u(U,"xl"),Xa=u(U,"lg"),Ya=u(U,"md"),Za=u(U,"sm"),$a=u(U,"ty"),ab=u(U,"ut"),X=function(b){try{U(b);var d=e.j("Height"),f=e.j("Width"),
c=A;switch(b){case "ut":c=E;break;case "ty":c=D;break;case "sm":c=C;break;case "md":c=B;break;case "lg":c=A;break;case "xl":c=z;break;case "xxl":c=y}V(d,f,b,c);W()}catch(n){s(n,"seme")}},bb=function(b){try{P.push(b)}catch(d){s(d,"roec")}},Y=function(){if(S)try{for(var b=0,d;d=P[b];++b)d(i)}catch(f){s(f,"eoec")}},cb=function(b){try{return S=b}catch(d){s(d,"ear")}},db=function(){var b=e.j("Height"),d=e.j("Width"),f=A,c="lg";if(d<pa&&O)c="ut",f=E;else if(d<oa&&O)c="ty",f=D;else if(d<na||b<ja)c="sm",
f=C;else if(d<ma||b<ia)c="md",f=B;Ua&&(d>la&&b>ha&&(c="xl",f=z),d>ka&&b>ga&&(c="xxl",f=y));V(b,d,c,f);return c},W=function(){try{var b=t("gbx1");if(b){var d=a.rtl(t("gb")),f=b.clientWidth,b=f<=Sa,c=t("gb_70"),n=t("gbg4"),p=t("gbg6")||n;if(!v)if(c)v=c.clientWidth;else if(p)v=p.clientWidth;else return;if(!w){var q=t("gbg3");q&&(w=q.clientWidth)}var L=i.mo,r,k,j;switch(L){case "xxl":r=Ka;k=Ea;j=xa;break;case "xl":r=La;k=Fa;j=ya;break;case "md":r=Na;k=Ga;j=Aa;break;case "sm":r=Oa-F;k=Ha;j=Ba;break;case "ty":r=
Pa-F;k=Ia;j=Ca;break;case "ut":r=Qa-F;k=Ja;j=Da;break;default:r=Ma,k=I,j=za}var m=a.snw&&a.snw();m&&(j+=m+k);var m=v,x=t("gbg1");x&&(m+=x.clientWidth+k);(q=t("gbg3"))&&(m+=w+k);var Q=t("gbgs4dn");n&&!Q&&(m+=n.clientWidth+k);var ba=t("gbd4"),R=t("gb_71");R&&!ba&&(m+=R.clientWidth+k+I);m=Math.min(304,m);j+=r;var M=t("gbqfbw"),G=t("gbq4");G&&(j+=G.offsetWidth);M&&(M.style.display="",j+=M.clientWidth+Ra);var G=f-j,ca=t("gbqf"),da=t("gbqff"),h=a.gpcc&&a.gpcc();if(ca&&da&&!h){h=f-m-j;switch(L){case "ut":h=
Math.min(h,wa);h=Math.max(h,ra);break;case "ty":h=Math.min(h,va);h=Math.max(h,qa);break;case "xl":h=Math.min(h,ua);h=Math.max(h,H);break;case "xxl":h=Math.min(h,ta);h=Math.max(h,H);break;default:h=Math.min(h,sa),h=Math.max(h,H)}ca.style.maxWidth=h+"px";da.style.maxWidth=h+"px";G-=h}var g=t("gbgs3");if(g){var L=236>=G,ea=a.cc(g,"gbsbc");L&&!ea?(a.ca(g,"gbsbc"),a.close()):!L&&ea&&(a.cr(g,"gbsbc"),a.close())}g=G;x&&(x.style.display="",g-=x.clientWidth+k);q&&(q.style.display="",g-=q.clientWidth+k);n&&
!Q&&(g-=n.clientWidth+k);R&&!ba&&(g-=R.clientWidth+k+I);var n=Q?0:35,N=Q||t("gbi4t");if(N&&!c){g>n?(N.style.display="",N.style.maxWidth=g+"px"):N.style.display="none";p&&(p.style.width=g<v&&g>n?g+"px":"");var fa=t("gbgs4d"),p="left";v>g^d&&(p="right");N.style.textAlign=p;fa&&(fa.style.textAlign=p)}q&&0>g&&(g+=q.clientWidth,q.style.display="none");x&&0>g&&(g+=x.clientWidth,x.style.display="none");if(M&&(0>g||c&&g<c.clientWidth))M.style.display="none";var c=d?"right":"left",d=d?"left":"right",J=t("gbu"),
gb=""!=J.style[c];b?(J.style[c]=f-J.clientWidth-r+"px",J.style[d]="auto"):(J.style[c]="",J.style[d]="");b!=gb&&a.swsc&&a.swsc(b)}}catch(hb){s(hb,"cb")}},V=function(b,d,f,c){i={};i.mo=f;i.vh=b;i.vw=d;i.es=c;f!=l&&(Y(),e.f&&e.f())},eb=function(b){y.h+=b;z.h+=b;A.h+=b;B.h+=b;C.h+=b;D.h+=b;E.h+=b},fb=function(){return i},ib=function(){try{if(!0==S){var b=l;l=db();if(b!=l)switch(l){case "ut":ab();break;case "ty":$a();break;case "sm":Za();break;case "md":Ya();break;case "xl":Wa();break;case "xxl":Va();
break;default:Xa()}}W()}catch(d){s(d,"sem")}},T=function(b){var d=t("gb");d&&Z(d,"gbexxli gbexli  gbemi gbesi gbeti gbeui".split(" "));for(var d=[],f=0,c;c=Ta[f];f++)if(c=t(c)){switch(b){case "gbexxl":Z(c,"gbexl  gbem gbes gbet gbeu".split(" "));a.ca(c,b);break;case "gbexl":Z(c,"gbexxl  gbem gbes gbet gbeu".split(" "));a.ca(c,b);break;case "":Z(c,"gbexxl gbexl gbem gbes gbet gbeu".split(" "));a.ca(c,b);break;case "gbem":Z(c,"gbexxl gbexl  gbes gbet gbeu".split(" "));a.ca(c,b);break;case "gbes":Z(c,
"gbexxl gbexl  gbem gbet gbeu".split(" "));a.ca(c,b);break;case "gbet":Z(c,"gbexxl gbexl  gbem gbes gbeu".split(" "));a.ca(c,b);break;case "gbeu":Z(c,"gbexxl gbexl  gbem gbes gbet".split(" ")),a.ca(c,b)}d.push(c)}return d},Z=function(b,d){for(var f=0,c=d.length;f<c;++f)d[f]&&a.cr(b,d[f])},jb=function(){try{if(!0==S)switch(db()){case "ut":$("gbeui");break;case "ty":$("gbeti");break;case "sm":$("gbesi");break;case "md":$("gbemi");break;case "xl":$("gbexli");break;case "xxl":$("gbexxli");break;default:$("")}W()}catch(b){s(b,
"semol")}},$=function(b){var d=t("gb");d&&a.ca(d,b)};a.eli=jb;a.elg=ib;a.elxxl=u(X,"xxl");a.elxl=u(X,"xl");a.ell=u(X,"lg");a.elm=u(X,"md");a.els=u(X,"sm");a.elr=fb;a.elc=bb;a.elx=Y;a.elh=eb;a.ela=cb;a.elp=W;a.upel=u(X,"lg");a.upes=u(X,"md");a.upet=u(X,"sm");jb();ib();a.mcf("el",{});}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;var d=function(){return document.getElementById("gbqfqw")},h=function(){return document.getElementById("gbqfq")},i=function(){return document.getElementById("gbqf")},j=function(){return document.getElementById("gbqfb")},l=function(b){var c=document.getElementById("gbqfaa");c.appendChild(b);k()},m=function(b){var c=document.getElementById("gbqfab");c.appendChild(b);k()},k=function(){var b=document.getElementById("gbqfqwb");if(b){var c=document.getElementById("gbqfaa"),e=document.getElementById("gbqfab");
if(c||e){var f="left",g="right";a.rtl(document.getElementById("gb"))&&(f="right",g="left");c&&(b.style[f]=c.offsetWidth+"px");e&&(b.style[g]=e.offsetWidth+"px")}}},n=function(b){a.qm(function(){a.qfhi(b)})};a.qfgw=d;a.qfgq=h;a.qfgf=i;a.qfas=l;a.qfae=m;a.qfau=k;a.qfhi=n;a.qfsb=j;}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;a.mcf("pm",{p:""});}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;a.mcf("mm",{s:"1"});}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{var a=window.gbar;var b=a.i;a.bcf("op",{url:"//ssl.gstatic.com/gb/js/om_bf2c42c9f9b68b13c54248651603a652.js"});var d=function(c){b.d(c);a.aq("op",function(){b.e()});c=function(){a.lb("op")};a.mdi.wg?c():a.qm(c)};b.e=d;a.mcf("op",{l:"zh-CN",u:b.c("0",0)});}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();
(function(){try{window.gbar.rdl();}catch(e){window.gbar&&gbar.logger&&gbar.logger.ml(e,{"_sn":"cfg.init"});}})();

_HAS_GPLUS_ENABLED = true;
_IS_DEBUG_IP = false;
_ON_LOGIN_PROMOTION = {title:'Google Reader will not be available after July 1, 2013',body:'\74a href\75\42http://support.google.com/reader/bin/answer.py?answer\0753028851\42\76Learn more\74a/\76.',version:2012};
function displayLoadingError() {
function setDisplay(id, display) {
var node = document.getElementById(id);
if (node) {
node.style.display = display;
}
}
setDisplay('loading-error', '');
setDisplay('main', 'none');
setDisplay('top-bar', 'none');
}
var _STUCK_TIMEOUT = window.setTimeout(function() {
new Image().src =
"/reader/js-load-error" +
"?src=" + encodeURIComponent("/reader/ui/2973113412-zh-CN-scroll.js?hl\x3dzh-CN") +
"&u=" + encodeURIComponent("04615556534921976030") +
"&type=" + encodeURIComponent("stuck") +
"&ck=" + (new Date().getTime());
displayLoadingError();
}, 30000);
